# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createFlightGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_createFlightDialog(object):
    def setupUi(self, createFlightDialog):
        createFlightDialog.setObjectName("createFlightDialog")
        createFlightDialog.resize(500, 280)
        createFlightDialog.setMinimumSize(QtCore.QSize(500, 280))
        createFlightDialog.setMaximumSize(QtCore.QSize(500, 280))
        font = QtGui.QFont()
        font.setPointSize(11)
        createFlightDialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(createFlightDialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 120, 81, 121))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(createFlightDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 390, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.departureAirportLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.departureAirportLabel.setObjectName("departureAirportLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.departureAirportLabel)
        self.departureAirportLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.departureAirportLineEdit.setMaxLength(3)
        self.departureAirportLineEdit.setObjectName("departureAirportLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.departureAirportLineEdit)
        self.arrivalAirportLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.arrivalAirportLabel.setObjectName("arrivalAirportLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.arrivalAirportLabel)
        self.arrivalAirportLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.arrivalAirportLineEdit.setMaxLength(3)
        self.arrivalAirportLineEdit.setObjectName("arrivalAirportLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.arrivalAirportLineEdit)
        self.departureDateTimeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.departureDateTimeLabel.setObjectName("departureDateTimeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.departureDateTimeLabel)
        self.departureDateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.departureDateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.departureDateTimeEdit.setCalendarPopup(True)
        self.departureDateTimeEdit.setObjectName("departureDateTimeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.departureDateTimeEdit)
        self.line = QtWidgets.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.flightNumberLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.flightNumberLineEdit.setToolTip("")
        self.flightNumberLineEdit.setInputMask("")
        self.flightNumberLineEdit.setText("")
        self.flightNumberLineEdit.setMaxLength(3)
        self.flightNumberLineEdit.setFrame(True)
        self.flightNumberLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.flightNumberLineEdit.setCursorPosition(0)
        self.flightNumberLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.flightNumberLineEdit.setObjectName("flightNumberLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.flightNumberLineEdit)
        self.arrivalDateTimeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.arrivalDateTimeLabel.setObjectName("arrivalDateTimeLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.arrivalDateTimeLabel)
        self.arrivalDateTimeEdit = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.arrivalDateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.arrivalDateTimeEdit.setCalendarPopup(True)
        self.arrivalDateTimeEdit.setObjectName("arrivalDateTimeEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.arrivalDateTimeEdit)
        self.passengersEconomyLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passengersEconomyLabel.setObjectName("passengersEconomyLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.passengersEconomyLabel)
        self.passengersEconomySpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.passengersEconomySpinBox.setMaximum(999)
        self.passengersEconomySpinBox.setObjectName("passengersEconomySpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.passengersEconomySpinBox)
        self.passengersBusinessLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passengersBusinessLabel.setObjectName("passengersBusinessLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.passengersBusinessLabel)
        self.passengersBusinessSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.passengersBusinessSpinBox.setMaximum(999)
        self.passengersBusinessSpinBox.setObjectName("passengersBusinessSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.passengersBusinessSpinBox)
        self.passengersFirstLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passengersFirstLabel.setObjectName("passengersFirstLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.passengersFirstLabel)
        self.passengersFirstSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.passengersFirstSpinBox.setMaximum(999)
        self.passengersFirstSpinBox.setObjectName("passengersFirstSpinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.passengersFirstSpinBox)
        self.flightNumberLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.flightNumberLabel.setObjectName("flightNumberLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.flightNumberLabel)
        self.autoFillButton = QtWidgets.QPushButton(createFlightDialog)
        self.autoFillButton.setGeometry(QtCore.QRect(410, 40, 81, 24))
        self.autoFillButton.setDefault(True)
        self.autoFillButton.setObjectName("autoFillButton")
        self.departureDateTimeLabel.setBuddy(self.departureDateTimeEdit)

        self.retranslateUi(createFlightDialog)
        self.buttonBox.accepted.connect(createFlightDialog.accept)
        self.buttonBox.rejected.connect(createFlightDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(createFlightDialog)

    def retranslateUi(self, createFlightDialog):
        _translate = QtCore.QCoreApplication.translate
        createFlightDialog.setWindowTitle(_translate("createFlightDialog", "Dialog"))
        self.departureAirportLabel.setToolTip(_translate("createFlightDialog", "Enter IATA Code"))
        self.departureAirportLabel.setText(_translate("createFlightDialog", "Departure Airport"))
        self.departureAirportLineEdit.setToolTip(_translate("createFlightDialog", "Enter IATA Code"))
        self.departureAirportLineEdit.setPlaceholderText(_translate("createFlightDialog", "e.g. SIN"))
        self.arrivalAirportLabel.setText(_translate("createFlightDialog", "Arrival Airport"))
        self.arrivalAirportLineEdit.setPlaceholderText(_translate("createFlightDialog", "e.g. SIN"))
        self.departureDateTimeLabel.setText(_translate("createFlightDialog", "Departure Date/Time"))
        self.flightNumberLineEdit.setPlaceholderText(_translate("createFlightDialog", "e.g. 235"))
        self.arrivalDateTimeLabel.setText(_translate("createFlightDialog", "Arrival Date/Time"))
        self.passengersEconomyLabel.setText(_translate("createFlightDialog", "#Passengers (Economy)"))
        self.passengersBusinessLabel.setText(_translate("createFlightDialog", "#Passengers (Business)"))
        self.passengersFirstLabel.setText(_translate("createFlightDialog", "#Passengers (First)"))
        self.flightNumberLabel.setToolTip(_translate("createFlightDialog", "Enter Flight Number Here (Maximum 3 Numbers)"))
        self.flightNumberLabel.setText(_translate("createFlightDialog", "Flight Number"))
        self.autoFillButton.setText(_translate("createFlightDialog", "AutoFill"))

