# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createMealOptionGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_createMealOptionDialog(object):
    def setupUi(self, createMealOptionDialog):
        createMealOptionDialog.setObjectName("createMealOptionDialog")
        createMealOptionDialog.resize(500, 224)
        createMealOptionDialog.setMinimumSize(QtCore.QSize(500, 100))
        createMealOptionDialog.setMaximumSize(QtCore.QSize(500, 260))
        font = QtGui.QFont()
        font.setPointSize(11)
        createMealOptionDialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(createMealOptionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 10, 81, 111))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(createMealOptionDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 390, 206))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.mealIdLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.mealIdLabel.setObjectName("mealIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mealIdLabel)
        self.mealIdLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mealIdLineEdit.setToolTip("")
        self.mealIdLineEdit.setInputMask("")
        self.mealIdLineEdit.setText("")
        self.mealIdLineEdit.setMaxLength(3)
        self.mealIdLineEdit.setFrame(True)
        self.mealIdLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.mealIdLineEdit.setCursorPosition(0)
        self.mealIdLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.mealIdLineEdit.setObjectName("mealIdLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mealIdLineEdit)
        self.optionNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.optionNameLabel.setObjectName("optionNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.optionNameLabel)
        self.optionCodeLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.optionCodeLabel.setObjectName("optionCodeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.optionCodeLabel)
        self.colourLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.colourLabel.setObjectName("colourLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.colourLabel)
        self.weightLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.weightLabel.setObjectName("weightLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.weightLabel)
        self.weightSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.weightSpinBox.setMinimum(0)
        self.weightSpinBox.setMaximum(9999)
        self.weightSpinBox.setProperty("value", 0)
        self.weightSpinBox.setObjectName("weightSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.weightSpinBox)
        self.optionCodeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.optionCodeLineEdit.setToolTip("")
        self.optionCodeLineEdit.setInputMask("")
        self.optionCodeLineEdit.setText("")
        self.optionCodeLineEdit.setMaxLength(3)
        self.optionCodeLineEdit.setFrame(True)
        self.optionCodeLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.optionCodeLineEdit.setCursorPosition(0)
        self.optionCodeLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.optionCodeLineEdit.setObjectName("optionCodeLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.optionCodeLineEdit)
        self.unitsUpliftedLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.unitsUpliftedLabel.setObjectName("unitsUpliftedLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.unitsUpliftedLabel)
        self.unitsUpliftedSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.unitsUpliftedSpinBox.setMaximum(999)
        self.unitsUpliftedSpinBox.setObjectName("unitsUpliftedSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.unitsUpliftedSpinBox)
        self.unitsLeftoverSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.unitsLeftoverSpinBox.setMaximum(999)
        self.unitsLeftoverSpinBox.setObjectName("unitsLeftoverSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.unitsLeftoverSpinBox)
        self.optionNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.optionNameLineEdit.setToolTip("")
        self.optionNameLineEdit.setInputMask("")
        self.optionNameLineEdit.setText("")
        self.optionNameLineEdit.setMaxLength(3)
        self.optionNameLineEdit.setFrame(True)
        self.optionNameLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.optionNameLineEdit.setCursorPosition(0)
        self.optionNameLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.optionNameLineEdit.setObjectName("optionNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.optionNameLineEdit)
        self.colourLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.colourLineEdit.setToolTip("")
        self.colourLineEdit.setInputMask("")
        self.colourLineEdit.setText("")
        self.colourLineEdit.setMaxLength(3)
        self.colourLineEdit.setFrame(True)
        self.colourLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.colourLineEdit.setCursorPosition(0)
        self.colourLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.colourLineEdit.setObjectName("colourLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.colourLineEdit)
        self.unitsLeftoverCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.unitsLeftoverCheckBox.setObjectName("unitsLeftoverCheckBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.unitsLeftoverCheckBox)

        self.retranslateUi(createMealOptionDialog)
        self.buttonBox.accepted.connect(createMealOptionDialog.accept)
        self.buttonBox.rejected.connect(createMealOptionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(createMealOptionDialog)

    def retranslateUi(self, createMealOptionDialog):
        _translate = QtCore.QCoreApplication.translate
        createMealOptionDialog.setWindowTitle(_translate("createMealOptionDialog", "Dialog"))
        self.mealIdLabel.setToolTip(_translate("createMealOptionDialog", "Enter Flight Number Here (Maximum 3 Numbers)"))
        self.mealIdLabel.setText(_translate("createMealOptionDialog", "Meal ID"))
        self.mealIdLineEdit.setPlaceholderText(_translate("createMealOptionDialog", "e.g. 15"))
        self.optionNameLabel.setText(_translate("createMealOptionDialog", "Option Name"))
        self.optionCodeLabel.setText(_translate("createMealOptionDialog", "Option Code"))
        self.colourLabel.setText(_translate("createMealOptionDialog", "Colour"))
        self.weightLabel.setText(_translate("createMealOptionDialog", "Weight"))
        self.weightSpinBox.setSuffix(_translate("createMealOptionDialog", " grams"))
        self.optionCodeLineEdit.setPlaceholderText(_translate("createMealOptionDialog", "e.g. F003"))
        self.unitsUpliftedLabel.setText(_translate("createMealOptionDialog", "Units Uplifted"))
        self.optionNameLineEdit.setPlaceholderText(_translate("createMealOptionDialog", "e.g. Chicken Noodles"))
        self.colourLineEdit.setPlaceholderText(_translate("createMealOptionDialog", "e.g. Blue"))
        self.unitsLeftoverCheckBox.setText(_translate("createMealOptionDialog", "Units Leftover"))

