# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchFlightGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_searchFlightDialog(object):
    def setupUi(self, searchFlightDialog):
        searchFlightDialog.setObjectName("searchFlightDialog")
        searchFlightDialog.resize(781, 355)
        searchFlightDialog.setMinimumSize(QtCore.QSize(500, 260))
        searchFlightDialog.setMaximumSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setPointSize(11)
        searchFlightDialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(searchFlightDialog)
        self.buttonBox.setGeometry(QtCore.QRect(690, 10, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(searchFlightDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.departureDateTimeCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.departureDateTimeCheckBox.setObjectName("departureDateTimeCheckBox")
        self.gridLayout.addWidget(self.departureDateTimeCheckBox, 4, 1, 1, 1)
        self.departureAirportCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.departureAirportCheckBox.setObjectName("departureAirportCheckBox")
        self.gridLayout.addWidget(self.departureAirportCheckBox, 2, 1, 1, 1)
        self.flightNumberCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.flightNumberCheckBox.setTristate(False)
        self.flightNumberCheckBox.setObjectName("flightNumberCheckBox")
        self.gridLayout.addWidget(self.flightNumberCheckBox, 1, 1, 1, 1)
        self.flightIdCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.flightIdCheckBox.setObjectName("flightIdCheckBox")
        self.gridLayout.addWidget(self.flightIdCheckBox, 0, 1, 1, 1)
        self.flightIdLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flightIdLineEdit.setToolTip("")
        self.flightIdLineEdit.setInputMask("")
        self.flightIdLineEdit.setText("")
        self.flightIdLineEdit.setMaxLength(3)
        self.flightIdLineEdit.setFrame(True)
        self.flightIdLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.flightIdLineEdit.setCursorPosition(0)
        self.flightIdLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.flightIdLineEdit.setObjectName("flightIdLineEdit")
        self.gridLayout.addWidget(self.flightIdLineEdit, 0, 2, 1, 1)
        self.passengersEconomyCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.passengersEconomyCheckBox.setObjectName("passengersEconomyCheckBox")
        self.gridLayout.addWidget(self.passengersEconomyCheckBox, 6, 1, 1, 1)
        self.arrivalCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.arrivalCheckBox.setObjectName("arrivalCheckBox")
        self.gridLayout.addWidget(self.arrivalCheckBox, 5, 1, 1, 1)
        self.departureAirportLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.departureAirportLineEdit.setMaxLength(3)
        self.departureAirportLineEdit.setObjectName("departureAirportLineEdit")
        self.gridLayout.addWidget(self.departureAirportLineEdit, 2, 2, 1, 1)
        self.arrivalAirportLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.arrivalAirportLineEdit.setMaxLength(3)
        self.arrivalAirportLineEdit.setObjectName("arrivalAirportLineEdit")
        self.gridLayout.addWidget(self.arrivalAirportLineEdit, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.arrivalDateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.arrivalDateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.arrivalDateTimeEdit.setCalendarPopup(True)
        self.arrivalDateTimeEdit.setObjectName("arrivalDateTimeEdit")
        self.horizontalLayout_2.addWidget(self.arrivalDateTimeEdit)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.arrivalDateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.arrivalDateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.arrivalDateTimeEdit_2.setCalendarPopup(True)
        self.arrivalDateTimeEdit_2.setObjectName("arrivalDateTimeEdit_2")
        self.horizontalLayout_2.addWidget(self.arrivalDateTimeEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.departureDateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.departureDateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.departureDateTimeEdit.setCalendarPopup(True)
        self.departureDateTimeEdit.setObjectName("departureDateTimeEdit")
        self.horizontalLayout.addWidget(self.departureDateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.departureDateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.departureDateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.departureDateTimeEdit_2.setCalendarPopup(True)
        self.departureDateTimeEdit_2.setObjectName("departureDateTimeEdit_2")
        self.horizontalLayout.addWidget(self.departureDateTimeEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.flightNumberLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flightNumberLineEdit.setToolTip("")
        self.flightNumberLineEdit.setInputMask("")
        self.flightNumberLineEdit.setText("")
        self.flightNumberLineEdit.setMaxLength(3)
        self.flightNumberLineEdit.setFrame(True)
        self.flightNumberLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.flightNumberLineEdit.setCursorPosition(0)
        self.flightNumberLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.flightNumberLineEdit.setObjectName("flightNumberLineEdit")
        self.gridLayout.addWidget(self.flightNumberLineEdit, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.passengersEconomySpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.passengersEconomySpinBox.setMaximum(999)
        self.passengersEconomySpinBox.setObjectName("passengersEconomySpinBox")
        self.horizontalLayout_4.addWidget(self.passengersEconomySpinBox)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setIndent(18)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.passengersEconomySpinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.passengersEconomySpinBox_2.setMaximum(999)
        self.passengersEconomySpinBox_2.setObjectName("passengersEconomySpinBox_2")
        self.horizontalLayout_4.addWidget(self.passengersEconomySpinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 6, 2, 1, 1)
        self.arrivalAirportLabelCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.arrivalAirportLabelCheckBox.setObjectName("arrivalAirportLabelCheckBox")
        self.gridLayout.addWidget(self.arrivalAirportLabelCheckBox, 3, 1, 1, 1)
        self.passengersBusinessCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.passengersBusinessCheckBox.setObjectName("passengersBusinessCheckBox")
        self.gridLayout.addWidget(self.passengersBusinessCheckBox, 7, 1, 1, 1)
        self.passengersFirstCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.passengersFirstCheckBox.setObjectName("passengersFirstCheckBox")
        self.gridLayout.addWidget(self.passengersFirstCheckBox, 8, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.passengersBusinessSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.passengersBusinessSpinBox.setMaximum(999)
        self.passengersBusinessSpinBox.setObjectName("passengersBusinessSpinBox")
        self.horizontalLayout_5.addWidget(self.passengersBusinessSpinBox)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(18)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.passengersBusinessSpinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.passengersBusinessSpinBox_2.setMaximum(999)
        self.passengersBusinessSpinBox_2.setObjectName("passengersBusinessSpinBox_2")
        self.horizontalLayout_5.addWidget(self.passengersBusinessSpinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setIndent(0)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.passengersFirstSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.passengersFirstSpinBox.setMaximum(999)
        self.passengersFirstSpinBox.setObjectName("passengersFirstSpinBox")
        self.horizontalLayout_6.addWidget(self.passengersFirstSpinBox)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setIndent(18)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.passengersFirstSpinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.passengersFirstSpinBox_2.setMaximum(999)
        self.passengersFirstSpinBox_2.setObjectName("passengersFirstSpinBox_2")
        self.horizontalLayout_6.addWidget(self.passengersFirstSpinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 8, 2, 1, 1)

        self.retranslateUi(searchFlightDialog)
        self.buttonBox.accepted.connect(searchFlightDialog.accept)
        self.buttonBox.rejected.connect(searchFlightDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(searchFlightDialog)

    def retranslateUi(self, searchFlightDialog):
        _translate = QtCore.QCoreApplication.translate
        searchFlightDialog.setWindowTitle(_translate("searchFlightDialog", "Dialog"))
        self.departureDateTimeCheckBox.setText(_translate("searchFlightDialog", "Departure Date/Time"))
        self.departureAirportCheckBox.setText(_translate("searchFlightDialog", "Departure Airport"))
        self.flightNumberCheckBox.setText(_translate("searchFlightDialog", "Flight Number"))
        self.flightIdCheckBox.setText(_translate("searchFlightDialog", "Flight ID"))
        self.flightIdLineEdit.setPlaceholderText(_translate("searchFlightDialog", "e.g. 15"))
        self.passengersEconomyCheckBox.setText(_translate("searchFlightDialog", "#Passengers (Economy)"))
        self.arrivalCheckBox.setText(_translate("searchFlightDialog", "Arrival Date/Time"))
        self.departureAirportLineEdit.setToolTip(_translate("searchFlightDialog", "Enter IATA Code"))
        self.departureAirportLineEdit.setPlaceholderText(_translate("searchFlightDialog", "e.g. SIN"))
        self.arrivalAirportLineEdit.setPlaceholderText(_translate("searchFlightDialog", "e.g. SIN"))
        self.label_3.setText(_translate("searchFlightDialog", "between"))
        self.label_6.setText(_translate("searchFlightDialog", "and"))
        self.label.setText(_translate("searchFlightDialog", "between"))
        self.label_2.setText(_translate("searchFlightDialog", "and"))
        self.flightNumberLineEdit.setPlaceholderText(_translate("searchFlightDialog", "e.g. 235"))
        self.label_5.setText(_translate("searchFlightDialog", "between"))
        self.label_8.setText(_translate("searchFlightDialog", "and"))
        self.arrivalAirportLabelCheckBox.setText(_translate("searchFlightDialog", "Arrival Airport"))
        self.passengersBusinessCheckBox.setText(_translate("searchFlightDialog", "#Passengers (Business)"))
        self.passengersFirstCheckBox.setText(_translate("searchFlightDialog", "#Passengers (First)"))
        self.label_7.setText(_translate("searchFlightDialog", "between"))
        self.label_9.setText(_translate("searchFlightDialog", "and"))
        self.label_10.setText(_translate("searchFlightDialog", "between"))
        self.label_11.setText(_translate("searchFlightDialog", "and"))

