# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchMealScheduleGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_searchMealScheduleDialog(object):
    def setupUi(self, searchMealScheduleDialog):
        searchMealScheduleDialog.setObjectName("searchMealScheduleDialog")
        searchMealScheduleDialog.resize(666, 198)
        searchMealScheduleDialog.setMinimumSize(QtCore.QSize(500, 190))
        searchMealScheduleDialog.setMaximumSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setPointSize(11)
        searchMealScheduleDialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(searchMealScheduleDialog)
        self.buttonBox.setGeometry(QtCore.QRect(580, 10, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(searchMealScheduleDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.flightIdLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flightIdLineEdit.setToolTip("")
        self.flightIdLineEdit.setInputMask("")
        self.flightIdLineEdit.setText("")
        self.flightIdLineEdit.setMaxLength(3)
        self.flightIdLineEdit.setFrame(True)
        self.flightIdLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.flightIdLineEdit.setCursorPosition(0)
        self.flightIdLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.flightIdLineEdit.setObjectName("flightIdLineEdit")
        self.gridLayout.addWidget(self.flightIdLineEdit, 1, 2, 1, 1)
        self.mealIdLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mealIdLineEdit.setToolTip("")
        self.mealIdLineEdit.setInputMask("")
        self.mealIdLineEdit.setText("")
        self.mealIdLineEdit.setMaxLength(3)
        self.mealIdLineEdit.setFrame(True)
        self.mealIdLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.mealIdLineEdit.setCursorPosition(0)
        self.mealIdLineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.mealIdLineEdit.setObjectName("mealIdLineEdit")
        self.gridLayout.addWidget(self.mealIdLineEdit, 0, 2, 1, 1)
        self.mealTypeCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.mealTypeCheckBox.setObjectName("mealTypeCheckBox")
        self.gridLayout.addWidget(self.mealTypeCheckBox, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.timeServedDateTimeEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.timeServedDateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.timeServedDateTimeEdit.setCalendarPopup(True)
        self.timeServedDateTimeEdit.setObjectName("timeServedDateTimeEdit")
        self.horizontalLayout.addWidget(self.timeServedDateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.timeServedDateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.timeServedDateTimeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 9, 1), QtCore.QTime(0, 0, 0)))
        self.timeServedDateTimeEdit_2.setCalendarPopup(True)
        self.timeServedDateTimeEdit_2.setObjectName("timeServedDateTimeEdit_2")
        self.horizontalLayout.addWidget(self.timeServedDateTimeEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.mealIdCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.mealIdCheckBox.setObjectName("mealIdCheckBox")
        self.gridLayout.addWidget(self.mealIdCheckBox, 0, 1, 1, 1)
        self.timeServedCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.timeServedCheckBox.setObjectName("timeServedCheckBox")
        self.gridLayout.addWidget(self.timeServedCheckBox, 3, 1, 1, 1)
        self.flightIdCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.flightIdCheckBox.setTristate(False)
        self.flightIdCheckBox.setObjectName("flightIdCheckBox")
        self.gridLayout.addWidget(self.flightIdCheckBox, 1, 1, 1, 1)
        self.mealTypeComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.mealTypeComboBox.setEditable(True)
        self.mealTypeComboBox.setObjectName("mealTypeComboBox")
        self.mealTypeComboBox.addItem("")
        self.mealTypeComboBox.addItem("")
        self.mealTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.mealTypeComboBox, 2, 2, 1, 1)

        self.retranslateUi(searchMealScheduleDialog)
        self.buttonBox.accepted.connect(searchMealScheduleDialog.accept)
        self.buttonBox.rejected.connect(searchMealScheduleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(searchMealScheduleDialog)

    def retranslateUi(self, searchMealScheduleDialog):
        _translate = QtCore.QCoreApplication.translate
        searchMealScheduleDialog.setWindowTitle(_translate("searchMealScheduleDialog", "Dialog"))
        self.flightIdLineEdit.setPlaceholderText(_translate("searchMealScheduleDialog", "e.g. 15"))
        self.mealIdLineEdit.setPlaceholderText(_translate("searchMealScheduleDialog", "e.g. 20"))
        self.mealTypeCheckBox.setText(_translate("searchMealScheduleDialog", "Meal Type"))
        self.label.setText(_translate("searchMealScheduleDialog", "between"))
        self.label_2.setText(_translate("searchMealScheduleDialog", "and"))
        self.mealIdCheckBox.setText(_translate("searchMealScheduleDialog", "Meal ID"))
        self.timeServedCheckBox.setText(_translate("searchMealScheduleDialog", "Time Served"))
        self.flightIdCheckBox.setText(_translate("searchMealScheduleDialog", "Flight ID"))
        self.mealTypeComboBox.setItemText(0, _translate("searchMealScheduleDialog", "Breakfast"))
        self.mealTypeComboBox.setItemText(1, _translate("searchMealScheduleDialog", "Lunch"))
        self.mealTypeComboBox.setItemText(2, _translate("searchMealScheduleDialog", "Dinner"))

